-- migrate:up
CREATE TABLE Pets (
  PetID INT AUTO_INCREMENT PRIMARY KEY,
  OwnerID INT NOT NULL,
  Name VARCHAR(255) NOT NULL,
  PetType VARCHAR(255) NOT NULL,
  IsMintedAsNFT BOOLEAN DEFAULT FALSE,
  CreatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (OwnerID) REFERENCES Users(UserID)
);

-- migrate:down
DROP TABLE Pets;
